import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import GlobalContext  from "./GlobalContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--primary",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--secondary",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Sakshat | Peer to Peer video chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalContext>
          {children}
        </GlobalContext>
        <Toaster position="bottom-center"/>
      </body>
    </html>
  );
}
